style:
  MagicNumber:
    ignoreEnums: true
    ignoreRanges: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - '10'
      - '100'
complexity:
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true
    ignoreSingleWhenExpression: true